language: c

compiler:
  - gcc

sudo: enabled

script:
- pwd
- ls
- sudo cmake -E make_directory build
- sudo cmake -E chdir build cmake ..
- sudo cmake --build build

matrix:
  include:
  - os: linux

